### ISSUE TITLE
play command parsing error

### ISSUE THREAD

**Issue by Yommy** [VTiS15/UNOBot#8]
Typing Red1 results in error.
![Screenshot 2022-10-09 102541](https://user-images.githubusercontent.com/4124991/194732157-216bfeef-6651-4240-8514-9fcb3f2932a0.png)

probably issue with regex at
https://github.com/VTiS15/UNOBot/blob/main/main.py#L5945

game mode is default.
using official bot

**Comment by VTiS15** [comment]
Yes it was a regex issue confusing the "d" in "Red" with the "d" in "d1" which is the draw 1 card in UNO Flip. It should be fixed now.
