### ISSUE TITLE
how to have the parameter list of the game modes and the codes for stack of cards?

### ISSUE THREAD

**Issue by Lexandjoy** [VTiS15/UNOBot#9]
I loved the game on discord, but I would like to have all the parameters to be able to configure the game mode and also things like pulling a card and continuing the turn of the round, please list them.

**Comment by VTiS15** [comment]
I have listed all the parameters and what you can do in-game in README.md. On Discord, you can also learn about the parameters by using the slash command `/u-sg help` and all in-game commands in your designated UNO channels.

**Comment by Lexandjoy** [comment]
Ok, but how I can set more then one setting? E.g: /u-sg args:stackcards on startingcards 10 7-0 on

**Comment by Lexandjoy** [comment]
Thank you very much!
